### ISSUE TITLE
Feature: edit (food/activity) entries

### ISSUE THREAD

**Issue by madmini** [simonoppowa/OpenNutriTracker#65]
Sometimes I enter the wrong amount of something. Currently the only way to correct this is to delete the entry and re-create it, which is cumbersome.

I would imagine a small ✏️ button or ⁝ menu with "edit" option on the item cards that open the add item form pre-filled with the appropriate values.

**Comment by vetinari** [comment]
Duplicate of #36?

**Comment by madmini** [comment]
yep, seems i missed that.

**Comment by madmini** [comment]
yep, seems i missed that.
